[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "arm-none-eabi-gdb -q -x openocd.gdb"

rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Lexamples/stm32h7",
]

[build]
target = "thumbv7em-none-eabihf"
